#服务器端口号
server:
  port: 8072

#分页插件配置（无需变更）
pagehelper:
  helperDialect: mysql
  page-size-zero: true
  params: count=countSql
  supportMethodsArguments: true

#spring基本配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/javal_model?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai


#日志地址 (注意!!! 需要配置自己的日志地址)
path.log: /Library/WebServer/log

#是否开启swagger开发文档
swagger:
  enable: true

#redis配置（无则不配）
redis:
  host: 192.168.1.155
  password:
  poolMaxIdle: 10
  poolMaxTotal: 10
  poolMaxWait: 3
  port: 6379
  timeout: 3

#minio基本配置（无则不配）
minio:
  accessKey: BCIAIOSFODNN7EXAMPLE
  secretKey: aKalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  endpoint: http://192.168.1.155:9000/

#权限管理配置（无则不配）
#超级管理员默认信息
super-admin-id: 1
super-admin-default-pwd: 123456
super-admin-default-user-name: admin


