#spring基本配置
spring:
  #配置文件相关配置
  profiles:
    active: mysql

  #查询数据是否去掉null
#  jackson:
#    default-property-inclusion: non_null

  #mvc相关配置
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /pages/
      suffix: .html
  #jmx相关配置
  jmx:
    enabled: false
  #资源相关配置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,
  #servlet相关配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

#日志插件配置
logging.config:
  classpath: logback-spring.xml

#mapper配置
mapper:
  mappers: com.dar.road.core.universal.Mapper

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
