#spring基本配置
spring:
  #配置文件相关配置
  profiles:
    active: mysql
    #jackson:
    #查询数据是否去掉null(因为自定义了configureMessageConverters所以这里不配)
    #    default-property-inclusion: non_null
    #配置时间格式化(因为自定义了configureMessageConverters所以这里不配)
    #date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8
  #servlet相关配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
# MyBatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.lylbp.project.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  # 通用枚举的扫描,支持统配符 * 或者 ; 分割
  type-enums-package: com.lylbp.project.enums
  # mybatis-plus-config.xml配置文件地址
  config-location: classpath:mybatis-config.xml
  #全局配置
  global-config:
    #数据库配置
    db-config:
      #主键类型
      id-type: UUID
      #字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      select-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #全局逻辑删除字段值 如果实体类上有 @TableLogic 则以实体上的为准，忽略全局。
      logic-delete-field: is_valid
      #逻辑已删除值（默认为1）
      logic-delete-value: 0
      #逻辑未删除值（默认为0）
      logic-not-delete-value: 1

##秘匙
#jasypt:
#  encryptor:
#    # 盐加密
#    password: lylbp
#    # 指定加密方式
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
